"""renamed to name_str

Revision ID: 676e361e7590
Revises: 
Create Date: 2025-12-05 08:42:41.362140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676e361e7590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_str', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('name_str')

    # ### end Alembic commands ###
