""" added reported

Revision ID: 7ce50dddc67a
Revises: 
Create Date: 2025-12-21 07:13:04.055503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce50dddc67a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reportedActions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reportedActions')
        batch_op.drop_column('reported')

    # ### end Alembic commands ###
