"""added selects

Revision ID: c951223123a6
Revises: e1dce171476a
Create Date: 2025-12-19 07:08:30.752783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c951223123a6'
down_revision = 'e1dce171476a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selects', sa.Text(), nullable=True))

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selects', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('selects')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('selects')

    # ### end Alembic commands ###
