"""changed to submission

Revision ID: dd0e60c8958d
Revises: be2ad58aea89
Create Date: 2025-12-07 11:53:07.827532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'dd0e60c8958d'
down_revision = 'be2ad58aea89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructor', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('adm', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('assignment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('units', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('at', sa.DateTime(), nullable=True))
        batch_op.drop_column('student_id')
        batch_op.drop_column('data')
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('at')
        batch_op.drop_column('units')
        batch_op.drop_column('assignment')
        batch_op.drop_column('topic')
        batch_op.drop_column('email')
        batch_op.drop_column('adm')
        batch_op.drop_column('phone')
        batch_op.drop_column('age')
        batch_op.drop_column('name')
        batch_op.drop_column('instructor')

    op.create_table('student',
    sa.Column('id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('instructor', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('age', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('adm', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=True),
    sa.Column('assignment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('units', sa.VARCHAR(length=255), nullable=True),
    sa.Column('at', sa.DATETIME(), nullable=True),
    sa.Column('form_id', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adm')
    )
    # ### end Alembic commands ###
