"""added device IP

Revision ID: e1dce171476a
Revises: cab2dd096a9f
Create Date: 2025-12-19 06:32:25.591285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dce171476a'
down_revision = 'cab2dd096a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip', sa.String(length=45), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('ip')

    # ### end Alembic commands ###
