"""added 2fa

Revision ID: ed99b9a18cec
Revises: e978bb7500cb
Create Date: 2025-12-13 12:06:17.311052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed99b9a18cec'
down_revision = 'e978bb7500cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devices', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('two_fa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('twofa_secret', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('twofa_secret')
        batch_op.drop_column('two_fa')
        batch_op.drop_column('devices')

    # ### end Alembic commands ###
